### ISSUE TITLE
Horizontal Bar Chart Component

### ISSUE THREAD

**Issue by imrenagi** [imrenagi/rojak-web-frontend#10]
We need a reusable chart component with these requirements:

1. It's recommended to use d3js as the visualization library
2. The json input will look like this:
```
{
 "short_name": "Agus-Silvy",
 "statistic": {
        "total_news": 1000,
        "total_pos_news": 500,
        "total_neg_news": 200,
        "total_neutral_news": 300
      }
}
```
3. The chart will have 3 y-axis values as shown in the wireframe (POSITF, NEGATIF, NEUTRAL).
4. For each bar, we want to see the total number of data for each y-axis value. This can be shown in text or shown as a dialog text shown on hover event
5. If it's possible, we want to see the percentage of positive, negative and neutral news that we have. 

![](http://res.cloudinary.com/imrenagi-com/image/upload/c_scale,w_783/v1506877640/Screen_Shot_2017-10-01_at_10.06.47_c8dchu.png)

**Comment by Flascher** [comment]
I'll give this one a shot.

**Comment by imrenagi** [comment]
Thanks @Flascher ! I really appreciate it!

**Comment by imrenagi** [comment]
Thanks @Flascher for the contribution!

**Comment by imrenagi** [comment]
Notes:
How to use this component:
```
import HorizontalBarChart from './../charts/HorizontalBarChart';

// TODO: remove me after testing complete
import testData from './../charts/test-data.json';

<HorizontalBarChart chartData={testData}/>
```
