### ISSUE TITLE
Setting up Configuration for React JS Unit Test

### ISSUE THREAD

**Issue by imrenagi** [imrenagi/rojak-web-frontend#11]
To resolve this issue, we might need your help to setup react js unit test and please provide with some documentation about how to add new unit test and how to run the existing unit test.

**Comment by jenniferkaplannyc** [comment]
Hi, I am happy to try to help with this project. Can you provide more information? What exactly is the issue?

**Comment by imrenagi** [comment]
Hi, thanks for your interest! basically we are planning to start doing BDD or TDD in react, but for now we haven't setup any configuration that enables us to do unit testing in this project. So we need your help to enables unit testing by installing several libraries required for unit test in react js(add some new libraries in package.json, give some working example of success unit test in react, etc). We also expect that you will give short documentation about what the other contributors need to do if they want to add unit test to this project. Does it makes more sense? Im sorry for the incomplete information before. 😄

**Comment by jenniferkaplannyc** [comment]
Hi, this is a large undertaking and honestly I'm not sure I have the time to dedicate to it. You will need to use Jest to test the React components. To help break this into a smaller project for me to work on, would it be possible to tell me of a static component in this repo and then I'll do my best to get a passing test for it? That will help others be able to write tests since there will be a template and the configuration will be done.

**Comment by imrenagi** [comment]
Hi, yeah I completely understand your concern. Right now, we just started developing a map component located in `/src/components/maps/IndonesiaMap.js`. There is a problem with that map. We are still using the hardcoded value of the map size. Our expectation is that the size of the map will change as the size of the screen is changing. Is that possible to add a unit test for that case? That's one of the components that I can think of to be tested. 😄

**Comment by ericadamski** [comment]
@jenniferkaplannyc if you would like some help on this I would be happy to, <3 TDD in React :)

**Comment by jenniferkaplannyc** [comment]
@ericadamski You can totally work on this! I am good at setting up Jest for snapshot tests.

**Comment by ericadamski** [comment]
@jenniferkaplannyc how do you want to split this up?

**Comment by jenniferkaplannyc** [comment]
@ericadamski You can do as much as you want! I am pretty busy and didn't realize how much time this would take.

**Comment by ericadamski** [comment]
I am on it @jenniferkaplannyc I will keep you up-to-date in case you want to jump back in 😄

**Comment by jenniferkaplannyc** [comment]
Thank you!

**Comment by ericadamski** [comment]
@imrenagi I see you are using feature branches, would you like me to open a feature branch using gitflow or fork your repo? I have forked it for now,  if you would like me to use git flow just let me know 🛩

**Comment by imrenagi** [comment]
please just ignore the feature branches. You can create PR from your forked repo 😄

**Comment by ericadamski** [comment]
@imrenagi using unit testing I am not sure you can test the issue you mentioned in `/src/components/maps/IndonesiaMap.js` I can provide some examples about how to TDD and snapshot your react components.

If you want to test window resize you will need some more complicated integration testing using phantom.js or something like that.

**Comment by imrenagi** [comment]
Yeah. You dont really have to test the map. Basically I just need to established unit test setup for this project. So, I need unit test setup and an example about how to test a sample component (You can create your sample component). it should be enough. Please include a bit of documentation if necessary to help the other contributors who want to try TDD in this project in the future. Does it make sense?

**Comment by ericadamski** [comment]
Yes that is perfect! @imrenagi I will test a few of your components and write some documentation in the readme about testing 😃

**Comment by imrenagi** [comment]
Cool. I'm looking forward to your PR, @ericadamski ! 👍
