### ISSUE TITLE
Fix incorrect position of media logo in media detail page

### ISSUE THREAD

**Issue by imrenagi** [imrenagi/rojak-web-frontend#14]
The media logo position should be in the top-middle of the screen. 

This is the current position of the logo. This is **incorrect**:
![](http://res.cloudinary.com/imrenagi-com/image/upload/c_scale,w_1333/v1507066520/Screen_Shot_2017-10-03_at_14.32.55_eoutom.png)

**The correct one should be**:
![](http://res.cloudinary.com/imrenagi-com/image/upload/c_scale,w_744/v1507066520/Screen_Shot_2017-10-03_at_14.30.32_hnj8aw.png)

Notes: 
* The js and css file is located `src/component/mediadetail`.
* To go to media detail page, you can click the `Media Detail Temp Button` from the homepage

**Comment by tygas** [comment]
Taking this one

**Comment by imrenagi** [comment]
Thanks @meetzaveri ! I will close this issue 😄
