### ISSUE TITLE
Add `Kunjungi Website` button in media detail page.

### ISSUE THREAD

**Issue by imrenagi** [imrenagi/rojak-web-frontend#16]
We need to add `Kunjungi Website` button to media detail page.
The requirements:
* The button will be located horizontally centered and under the media logo. 
* This button will redirect the user to the a new browser tab and open a url link given on the button metadata.
* You can use hardcoded url for now. Please use (https://facebook.com). So when the user click the button, it will be redirected to facebook page.
* You may use bootstrap component for this button.

The page component file is located in `src/components/mediadetail/MediaDetail.js`. 

Here is the wireframe:
![](http://res.cloudinary.com/imrenagi-com/image/upload/v1507066520/Screen_Shot_2017-10-03_at_14.30.32_hnj8aw.png)

**Comment by mdew192837** [comment]
I'll take care of this!

**Comment by mdew192837** [comment]
Do you used gitter? I have a question. @imrenagi

**Comment by imrenagi** [comment]
Nope, I don't @mdew192837

**Comment by mdew192837** [comment]
How do I access the media detail page? @imrenagi

**Comment by imrenagi** [comment]
There is a button named `Media Detail Temp Button` in `/`. The button will be inside `Media` section on the `/` page

**Comment by mdew192837** [comment]
Done! @imrenagi

**Comment by imrenagi** [comment]
Thanks! I'll review the PR really quick when I'm done with my work. 👍
