### ISSUE TITLE
Fix text alignment in news section in media detail page.

### ISSUE THREAD

**Issue by imrenagi** [imrenagi/rojak-web-frontend#17]
Currently in media detail page `src/components/mediadetail/MediaDetail.js`, we use `NewsSection` component. However, the text of the news section is not properly formatted. The correct one is left-justify text.

Notes: 
* Please make sure that when you change or create new css for this issue, you aren't changing the overriding the other's component css. 

The incorrect format:
![](http://res.cloudinary.com/imrenagi-com/image/upload/c_scale,w_1208/v1507068142/Screen_Shot_2017-10-03_at_15.01.15_mnermi.png)

The correct format:
![](http://res.cloudinary.com/imrenagi-com/image/upload/c_scale,w_925/v1507068177/Screen_Shot_2017-10-03_at_15.02.27_ixnh0o.png)

**Comment by dbrereton1995** [comment]
I'll do this 👍

**Comment by dbrereton1995** [comment]
Is this the solution you're after? I've only implemented it for those divs assigned the 'container-media' class.

<img width="946" alt="b6a081861d31e42620f62dc7a9e24fad" src="https://user-images.githubusercontent.com/10518422/31152172-d7dc0fa4-a892-11e7-83ef-be3314641ae4.png">

**Comment by imrenagi** [comment]
Yep. That's what I expect! Thanks. I'll review your PR very quick. Thanks for your contribution!
