### ISSUE TITLE
Multiple Donuts Chart Component

### ISSUE THREAD

**Issue by imrenagi** [imrenagi/rojak-web-frontend#8]
We need a reusable chart component with these requirements:
1. It's recommended to use d3js as the visualization library
2. It will accept 4 parameters:
* The number of candidate in an election
* The number of positive, negative, and neutral news.
2. The candidate_number will be shown in the middle of chart (see the wireframe below)
3. The number of positive, negative and neutral news will be shown separately in 3 different colours (Red for negative, green for positive, and blue for neutral). 

. ![wireframe](http://res.cloudinary.com/imrenagi-com/image/upload/c_scale,w_422/v1506926167/Chart-3_scbkse.jpg)

**Comment by viettrung9012** [comment]
@imrenagi I'd like to take a stab on this, but before I start I have a question:
What is one full circle value, is it be one candidate's total news? Or is it a number provided by the component caller/creator?
The former is harder to compare amongst candidates, and it can work with only one donut chart
The latter will need an additional parameter provided by the caller

**Comment by wildan3105** [comment]
I'd like to work on this :smile:. Where do I start?

**Comment by imrenagi** [comment]
Hi @wildan3105 . Thanks for your interest. You can start forking this project and implements this chart in as a separate component. There will be a folder `src/components/chart`. So you can add your js file and css there. You can create a new folder inside of it, if you need it. If you need a reference about how to use d3 in react js. There is a previous PR #12 in this project that worked on d3 js. So you can use it as a reference. But, the requirement for that PR is different. Let me know if you still have some confusion.

**Comment by wildan3105** [comment]
Ok will do that accordingly :ok:
