### ISSUE TITLE
Horizontal Stack Bar Chart Component

### ISSUE THREAD

**Issue by imrenagi** [imrenagi/rojak-web-frontend#9]
We need a reusable chart component with these requirements:

1. It's recommended to use d3js as the visualization library
2. The json input will look like this:
```
{
"total_news": 789,
"candidates": [
                {
                    "short_name": "Agus-Silvy",
                    "statistic": {
                        "total_news": 200,
                        "total_pos_news": 100,
                        "total_neg_news": 50,
                        "total_neutral_news": 50 
                    }
                },
                {
                    "short_name": "Ahok-Djarot",
                    "statistic": {
                        "total_news": 300,
                        "total_pos_news": 100,
                        "total_neg_news": 100,
                        "total_neutral_news": 100 
                    }
                },
                {
                    "short_name": "Anies-Sandi",
                    "statistic": {
                        "total_news": 200,
                        "total_pos_news": 100,
                        "total_neg_news": 50,
                        "total_neutral_news": 50 
                    }
                },
            ]
}
```
3. The name of the each bar is not necessary to be located on the right side of the bar. It can be inside the bar chart.
4. You are allowed to add legend and/or the x-axis to give more information about the chart
5. (Optional) If user hover the mouse to the chart, user will be able to see the number detail of the chart (#positive/#negative/#neutral.

![](http://res.cloudinary.com/imrenagi-com/image/upload/c_scale,w_632/v1506874673/Screen_Shot_2017-10-01_at_08.59.01_kk6skf.png)

**Comment by pranay414** [comment]
@imrenagi I would like to take up this issue.

**Comment by imrenagi** [comment]
Thanks @pranay414 ! I'm looking forward to your PR 👍

**Comment by imrenagi** [comment]
Hi @pranay414 are you still on this issue?

**Comment by pranay414** [comment]
@imrenagi Yes, I am working on it.

**Comment by pranay414** [comment]
@imrenagi I have found this: http://www.reactd3.org/. Can I use this to create component?

**Comment by imrenagi** [comment]
Yes, please. We can review your PR later about how you use that library.

**Comment by imrenagi** [comment]
FYI @pranay414 , we already have d3 installed in our package.json, but not reactd3
